### ISSUE TITLE
Update requirements list in Windows

### ISSUE THREAD

**Issue by viguera** [zengfu94/MicrosoftRewards#1]
Seems like the default Windows install does not include requests or bs4, which are needed for the script to run.

I'd suggest an amendment to the README to include installing get-pip (which will install pip, setuptools and wheel) or easy_install.

https://bootstrap.pypa.io/get-pip.py

Then installing / updating everything.

python -m pip install -U bs4 requests setuptools pip

**Comment by zengfu94** [comment]
Great idea, you can submit a PR or I'll get to it after sleep (late here)

**Comment by zengfu94** [comment]
I've made the changes, check at last two commits

**Comment by Brenex** [comment]
Thanks, was getting the following error till I ran the above PIP command:

Traceback (most recent call last):
  File "C:\Users\Danny\Downloads\MicrosoftRewards\bing.py", line 2, in <module>
    import wikipedia as wiki
  File "C:\Users\Danny\Downloads\MicrosoftRewards\wikipedia.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by zengfu94** [comment]
@Brenex added a catch in latest commit, thanks
