### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#11]
hi it's still give me this error

Traceback (most recent call last):
  File "D:\GitHub\z_xbmc\New BR\bing.py", line 104, in report_account
    form = BS(res.content, "html.parser").findAll("form")[0]
IndexError: list index out of range

my accounts.txt as
****@outlook.com>******>>Mozilla/5.0 (Windows NT 6.1; rv:53.0) Gecko/20100101 Firefox/53.0>Mozilla/5.0 (Linux; Android 7.1.2; Nexus 5X Build/N2G47O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36>127.0.0.1:8080

**Comment by rrosajp** [comment]
also i pull git today so all updated

**Comment by zengfu94** [comment]
Remove this: >127.0.0.1:8080

**Comment by rrosajp** [comment]
i did removed that but not working btw i have other ac with @hotmail.com it work ! but this outlook.com not working

**Comment by zengfu94** [comment]
okay so when you update and run again upload the failed.html file

**Comment by rrosajp** [comment]
here is the file i uploded
<a href=http://www.filedropper.com/failed><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file backup online</a></div>
some how i cannot uplode this type of file here so the link is up here

**Comment by zengfu94** [comment]
please git pull and run again, the script should retry until it works
