### ISSUE TITLE
[Feature Requests] UI feedback elements

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#12]
Hi,

Based on having used sealemar/BingRewards for a while and now zengfu94/MicrosoftRewards there are a few things I'd love to see implemented that I miss from sealemar/BingRewards (and I appreciate some/many/all of these may already be in your head on a roadmap and you get the foundations finished off!)

1. Feedback on how many Desktop/Mobile searches need to be completed for each account, and when running multiple accounts, when an account is complete. Right now, all that is shown on screen while executing is "account: search" and then next line "account: next search in: X seconds". I don't know how many more searches need to be completed to hit max. point generating searches per day in desktop and mobile. sealemar/BingRewards has a rolling count, e.g. 3/42 to indicate 3rd search of 42 which is helpful to know how long until completion, and validate that the number of searches to be performed is inline with what we are seeing on the official Rewards webpage for desktop/mobile searches remaining.

2. Report at end confirming how many searches and points earned. Would be great if this could be written out to a log file for reference.

**Comment by zengfu94** [comment]
lol the second one is already there :P

**Comment by zengfu94** [comment]
Ill add the first ho

**Comment by AnthonyBe** [comment]
Re. the final report.. OK.. I had been seeing it written out inconsistently so wasn't sure whether it was an end-of-processing report or something the script used internally during execution. I'll keep a closer eye when the script I launched today completes.

**Comment by zengfu94** [comment]
the report may look off if an account errors or has a retry, ill work on first suggestion tommorrow. if u have anymore feel free to posr here

**Comment by zengfu94** [comment]
its also only written after all accounts are done. im gonna add writing accounts that failed to it
