### ISSUE TITLE
10 point search not being performed

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#13]
Grabbed current git pull but had suspected the 10 point search was not being performed even before.

For example, today when I ran it said in the script execution "Bikes in Norway"

On one account I knew I had already clicked on it so it didn't matter (any way to validate whether it has already been done and indicate as such?)
On another account, I knew it hadn't been done, and even after script had commenced desktop/mobile searches, when I went to the MS Rewards website, the 'Bikes in Norway' 10 point search was still available.

**Comment by zengfu94** [comment]
It doesnt complete right at the beginning, it does it randomly throughout searching period.

**Comment by zengfu94** [comment]
ill run a quick test to make sure

**Comment by AnthonyBe** [comment]
"It doesn't complete right at the beginning, it does it randomly throughout searching period."

Ah! OK, Didn't realise that. Assumed it would do it before the searches.

**Comment by zengfu94** [comment]
okay latest commit now does offers at login since the more i thought about it the more humanlike it is

**Comment by AnthonyBe** [comment]
Awesome! Thanks! I was think the same (i.e. click the free stuff immediately)

**Comment by zengfu94** [comment]
it should also do the 10 point search in edge, thanks for bringing to my attention

**Comment by AnthonyBe** [comment]
Hmmm... it has broken something:

C:\Users\Anthony>"D:\Python27\python.exe" C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 290
    querytime = random.randint(c.querytime_low,c.querytime_high)
            ^
SyntaxError: invalid syntax

**Comment by zengfu94** [comment]
Fixed

**Comment by AnthonyBe** [comment]
Confirmed :)
