### ISSUE TITLE
[Enhancement] Language and Localization support

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#14]
Possibly just a question, or an enhancement.

Microsoft Rewards is available in numerous countries/languages:

Australia: English
France: French
Germany: German
United Kingdom: English
United States: English (Available in all 50 states and in Washington D.C. Not available in Puerto Rico.)

Ref: https://support.microsoft.com/en-us/help/4027275/microsoft-account-microsoft-rewards-regions-and-languages

I notice that in common.py all the settings are US-centric, e.g.
acceptLang = "en-US,en;q=0.5" (I would default to en-AU,en in Australia)
hostURL = "https://www.bing.com/" (I would default to https://www.bing.com/?cc=au in Australia)

Just wondering if there is an opportunity to make the script look more 'real' by better leveraging local language and URL?

**Comment by AnthonyBe** [comment]
oh... that should also extend to the Google Trends used to seed the searches being localized.

By default, it defaults to US trends (https://trends.google.com/trends/) but in my case, it would possibly be better if it drew from local (in my case, Australia) trends (https://trends.google.com/trends/home/all/AU).

**Comment by zengfu94** [comment]
Did you happen to find France or Germany links?
