### ISSUE TITLE
[Enhancement] Should config items move out of common.py

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#15]
Given every time I download a git pull I (should) overwite ALL files, I'm wondering if the user-config settings in common.py (e.g. ua querytime, etc) should move out into a file that doesn't come down in the git pull package each time. Similar to the way the accounts.txt is handled.

**Comment by zengfu94** [comment]
Good idea. For now you can run: git update-index --assume-unchanged common.py

**Comment by zengfu94** [comment]
Please review the past couple of changes and see if those were what you were thinking for suggestions. Haven't finished this one yet.
