### ISSUE TITLE
ValueError: sample larger than population

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#19]
accountremoved@domainremoved: logging in
accountremoved@domainremoved: current points: 11927
accountremoved@domainremoved: desktop left: 0
accountremoved@domainremoved: mobile left: 3
Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 303, in search_account
    querytimes = random.sample(range(1,int(querytime)),int(querysalt + mobile_left) - 1)
  File "D:\Python27\lib\random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

**Comment by zengfu94** [comment]
What did you set querytime to? This happens when it's less than number of searches being performed.

**Comment by AnthonyBe** [comment]
querytime_low = 5000
querytime_high = 8000

Should've been plenty of time for the 3 searches?

**Comment by zengfu94** [comment]
I'll push an update tomorrow to fix this stuff. Thanks for reporting with descriptive errors!
