### ISSUE TITLE
[Enhancement Request] separate salt for mobile and desktop

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#21]
is there any way to add salt separate for desktop and mobile
proportionately to total search left 

my common setting was
querysalt_low = 8
querysalt_high = 16
at start this was the case
*****@hotmail.com: desktop left: 30
*****@hotmail.com: mobile left: 20

actual search done by script as this one is the last count of search done on a/c
before search is done
mobile add 12 to total search
*****@hotmail.com: 32/20: mobile search: damon jones

where as desktop add only 5 to total search
*****@hotmail.com: 35/30: desktop search: episcopal church

this behavior i observing for 2 days and same thing happening 
more added to mobile then desktop

**Comment by zengfu94** [comment]
Abirtarily influencing random values and searching patterns seems like it defeats the purpose of them. It's all random, some people search more on their phones than desktops.
