### ISSUE TITLE
Login Failure with current git pull when selectedLocale = "Australia"

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#22]
Latest commit d1702c5
Tried multiple times, it failed with multiple accounts.

Found accounts.txt
sleeping for 241 seconds
ssleeping for 758 seconds
leeping for 977 seconds
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: logging in
Caught failed request on: accountremoved@domainremoved exiting...

**Comment by zengfu94** [comment]
Does it fail on commits prior to this or only this one?

**Comment by AnthonyBe** [comment]
Apologies, I missed some key detail in the original post :S

Error occurs when selectedLocale = "Australia"

Is fine when selectedLocale = "United States"

**Comment by zengfu94** [comment]
good to know! i will test some

**Comment by zengfu94** [comment]
common.py values are saved and rewritten thru the automatic updating. keep opening issues for suggestions 👍

**Comment by AnthonyBe** [comment]
hmmm... so if common.py is going to be checked and auto-updated, how does one customize settings in common.py without losing them via the auto-update?

**Comment by zengfu94** [comment]
The values you change them to are saved, the update is performed and then your values are written to the updated common.py

**Comment by AnthonyBe** [comment]
Ah. Cool 😁

Well, back to getting non US locale settings to work!

**Comment by zengfu94** [comment]
They work for searches but not for logging in atm.

**Comment by AnthonyBe** [comment]
All (login and searches) seems to be working fine as of current commit (cdf2961).
