### ISSUE TITLE
Copyright And License For wikipedia.py

### ISSUE THREAD

**Issue by amayer5125** [zengfu94/MicrosoftRewards#23]
You copied wikipedia.py from another project that was licensed under the LGPL. This stipulates that you must keep copyrights in tact. Please add the following lines back to the top of the wikipedia.py file.
```
# Wikipedia queries generator
# developed by Alex Mayer (2014)
```

You should also choose a license for your project. I think since most of this project is copied from another licensed under the LGPL that it should be the LGPL. If it is any other license please add a note to wikipedia.py that it is licensed under the LGPL and a copy of that license can be found at: https://www.gnu.org/licenses/lgpl-3.0.txt. You can just link it, you don't need the full text.

If you would like help making these changes just let me know and I can help you.

**Comment by zengfu94** [comment]
Added to wikipedia.py. I don't want to license the project.

**Comment by amayer5125** [comment]
You put the wrong copyright in the file. It should read literally:
```
# Wikipedia queries generator
# developed by Alex Mayer (2014)
```

Also it is a good idea to have a license on a project especially if you would like other people to use and contribute to it. This is a great resource if you are curious about differences https://choosealicense.com/
