### ISSUE TITLE
Automatic Updater just endlessly opening windows [Latest commit 4c474b4]

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#24]
As per title.

It just endlessly open CMD prompt windows which contain:

Checking for updates...
Saving common.py values...
Peforming update...
Configuring common.py
You can close this window now.

C:\Temp\MicrosoftRewards\MicrosoftRewards-master>

**Comment by zengfu94** [comment]
Forgot to let it know it already updated. Run it again please 👍

**Comment by AnthonyBe** [comment]
Have just stepped out for a few hours. Will test in about 6 hours' time.

**Comment by AnthonyBe** [comment]
Tried again using commit 4c474b4 - same issue (never-ending CMD prompt windows).

Grabbed latest commit (6b0eceb) and got "Git not found or updates disabled!" and then it continued on normally. Given I don't have Git on my system (I'm just downloading packages from web) this would appear to be working as intended?

**Comment by zengfu94** [comment]
Yes that's normal if you don't have git.

**Comment by zengfu94** [comment]
Also test with locale as Australia
