### ISSUE TITLE
sript not run on pi  ~Caught failed request on: 

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#27]
hi
 i try to run script on pi but it do not work on pi 
it log in ok but not retriving 
Git not found or updates disabled!

```
Found accounts.txt
sleeping for 8 seconds
****@gmail.com: logging in
****@gmail.com: current points: 0
Caught failed request on:  retrying...
```

here is the failed.html

`<html><head><title>Bing</title></head><body>Loading...<script type="text/javascript">//<![CDATA[
var _w = window; var o = _w.opener; var mainWindow; (mainWindow = o) || (mainWindow = _w.parent); 
if (mainWindow) {mainWindow.sj_evt && mainWindow.sj_evt.fire("wl:cancel"); };if (o) _w.close();;
//]]></script></body></html>`

**Comment by zengfu94** [comment]
Raspberry Pi must be wired, otherwise you'll have too many drops.

**Comment by RewardsMaster** [comment]
Still have the same errors.

**Comment by zengfu94** [comment]
@RewardsMaster Same as him?

**Comment by zengfu94** [comment]
Closing this since no updates and pi's aren't viable for constant network connectivity anyways.

**Comment by kkasberg** [comment]
I have it running on the pi fine.   I don't know why a pi would not be viable for constant network connectivity either.   I have had them up over 1 year before.

**Comment by zengfu94** [comment]
@kkasberg mine constantly drops connection, i think it's first generation tho.
