### ISSUE TITLE
Not able to run using task scheduler

### ISSUE THREAD

**Issue by Brenex** [zengfu94/MicrosoftRewards#28]
Now that there is the check for update script that runs, I can't get it to launch using task scheduled anymore. This is that it looks like:

![capture](https://user-images.githubusercontent.com/3178983/30811959-a22d0c80-a1d7-11e7-8798-cae933bf7c69.JPG)

If I double click the bing.py file it works fine although the second time it opens up it says "Git not found or updates disabled!" which is not true because it checked for updates in the previous instance that just closed after checking for updates.

**Comment by zengfu94** [comment]
Fixed in latest :)
