### ISSUE TITLE
Git not found or updates disabled Linux

### ISSUE THREAD

**Issue by kkasberg** [zengfu94/MicrosoftRewards#29]
I have git installed, and am not sure why it is failing the check.

```
~/MicrosoftRewards$` ./bing.py
Git not found or updates disabled!
```

**Comment by zengfu94** [comment]
I had only had linux in mind when I wrote the initial updater, please update and then wait for another update and report back.

**Comment by kkasberg** [comment]
I am now getting 

```
 python bing.py
  File "bing.py", line 44
    sesh = requests.Session()
       ^
SyntaxError: invalid syntax

```

**Comment by zengfu94** [comment]
try again please

**Comment by kkasberg** [comment]
Thanks, this is resolved.
