### ISSUE TITLE
In no proxy set SyntaxError: bing.py line 225 if proxy != "127.0.0.1:8080"

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#3]
Grabbed current code and just set username and password and left proxy as is (i.e. "proxy(optional)").

Error message:

  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 225
    if proxy != "127.0.0.1:8080"
                               ^
SyntaxError: invalid syntax

**Comment by zengfu94** [comment]
Just fixed, nice catch. if you're not using a proxy remove the >proxy(optional)

**Comment by AnthonyBe** [comment]
Removed it - still getting same error.

**Comment by zengfu94** [comment]
git pull

**Comment by AnthonyBe** [comment]
Resolved in new git pull :)

**Comment by zengfu94** [comment]
@AnthonyBe lemme know if you come across anything else, closing this
