### ISSUE TITLE
request to update since script not geting mobile left

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#30]
at bing.py line # 260 is 
	`		mobile_left = int(bep_progress.search(details[2].text.encode("utf-8")).group(2)) / c.searchValue - int(bep_progress.search(details[2].text.encode("utf-8")).group(2)) / c.searchValue
`

insted of 
`			mobile_left = int(bep_progress.search(details[2].text.encode("utf-8")).group(2)) / c.searchValue - int(bep_progress.search(details[2].text.encode("utf-8")).group(1)) / c.searchValue
`
it must b typo

**Comment by zengfu94** [comment]
fixed https://github.com/zengfu94/MicrosoftRewards/commit/519a2d120e209fa7c2d7683e90211ad0610cbfcc
