### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' when searches complete

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#32]
Using  commit 12aec7b
Error thrown when searches complete:

accountremoved@domainremoved.com: searches done
Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 289, in search_account
    newPoints = int(finder.search(page.content).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by zengfu94** [comment]
Are you still getting this?

**Comment by AnthonyBe** [comment]
I've been monitoring further and it seems to be more random that I originally thought.
I've seen it occur mid script-run a few times now, e.g.

accountremoved@domainremoved: 2/4: mobile search: john ritchie
accountremoved@domainremoved: searches done
Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 289, in search_account
    newPoints = int(finder.search(page.content).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: using saved cookies
accountremoved@domainremoved: current points: 4755
accountremoved@domainremoved: desktop left: 3
accountremoved@domainremoved: mobile left: 4
accountremoved@domainremoved: next search in: 33 seconds
accountremoved@domainremoved: 1/4: mobile search: gerphil flores
accountremoved@domainremoved: next search in: 136 seconds

Not quite sure what to make of it right now..

**Comment by zengfu94** [comment]
This should be fixed with latest commit, I have not seen it.
