### ISSUE TITLE
Not Completing Searches

### ISSUE THREAD

**Issue by Brenex** [zengfu94/MicrosoftRewards#33]
![messages image 3165289221](https://user-images.githubusercontent.com/3178983/30991111-b7e36884-a471-11e7-811d-daf505573674.png)

**Comment by zengfu94** [comment]
it can go below the amount with the query_salt_low value in common.py

**Comment by Brenex** [comment]
oh ok, thanks for the heads up!

**Comment by zengfu94** [comment]
Sometimes it's more humanlike not to complete all searches, just a heads-up.
