### ISSUE TITLE
Not earning points when locale = Australia

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#34]
I had been suspecting this for a week but wanted to do some testing using both Australia and US locales. I'm not pretty convinced that I'm not earning points when I set the locale to Australia even though the script is running fine.

Here is my test results today:

(Note: In common.py I've changed searchvalue to 3 (line 22) and the trends URL for US to be same as Australia so that when I'm testing locale set to US that the values work the same)

Starting point, my Rewards Dashboard flyout:

PC search 
Earn up to 90 points per day, 3 points per search on PC. Start with Australian news.
72 of 90 points
 
Mobile search 
Earn up to 60 points per day, 3 points per search on mobile.
30 of 60 points

Start running script with locale set to Australia:

```
accountremoved@domainremoved: using saved cookies
accountremoved@domainremoved: current points: 13211
accountremoved@domainremoved: desktop left: 6
accountremoved@domainremoved: mobile left: 10
accountremoved@domainremoved: next search in: 9 seconds
... lots of searches ...
accountremoved@domainremoved: 9/10: mobile search: mark nicholas
accountremoved@domainremoved: next search in: 47 seconds
accountremoved@domainremoved: 10/10: mobile search: roman catholic
accountremoved@domainremoved: searches done
Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 289, in search_account
    newPoints = int(finder.search(page.content).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

Caught failed request on: accountremoved@domainremoved retrying...
accountremoved@domainremoved: using saved cookies
accountremoved@domainremoved: current points: 13214
accountremoved@domainremoved: desktop left: 5
accountremoved@domainremoved: mobile left: 10
```

So, despite the script completing 10 mobile searches, my points only incremented by 3 and as per the last line, there was still 10 mobile searches to do (i.e. the 3 points came from a manual desktop search I did while script was running).

Validation check of my Rewards dashboard:

PC search 
Earn up to 90 points per day, 3 points per search on PC. Start with Australian news.
75 of 90 points

Mobile search 
Earn up to 60 points per day, 3 points per search on mobile.
30 of 60 points

Now, changed locale to United States and re-started script.

```
accountremoved@domainremoved: using saved cookies
accountremoved@domainremoved: current points: 13214
accountremoved@domainremoved: desktop left: 5
accountremoved@domainremoved: mobile left: 10
accountremoved@domainremoved: next search in: 165 seconds
accountremoved@domainremoved: 1/10: mobile search: popular now
accountremoved@domainremoved: next search in: 249 seconds
accountremoved@domainremoved: 2/10: mobile search: anita ekberg
accountremoved@domainremoved: next search in: 48 seconds
accountremoved@domainremoved: 3/10: mobile search: pirate
accountremoved@domainremoved: next search in: 440 seconds
```

PC search 
Earn up to 90 points per day, 3 points per search on PC. Start with Australian news.
75 of 90 points

Mobile search 
Earn up to 60 points per day, 3 points per search on mobile.
39 of 60 points

After only 3 mobile searches, the Rewards dashboard is reflecting the 9 points earned.

As stated originally, I had been suspecting this for about a week and doing some back and forth testing to rule out Dashboard data latency, etc. I now definitely believe there is something wrong with the script when I set locale to Australia even though the script shows no errors.

**Comment by AnthonyBe** [comment]
I haven't retested this for a while so will give it a go with the current code and see if anything has changed.

**Comment by AnthonyBe** [comment]
Using current commit (f2a893c) this is now working fine :)

**Comment by zengfu94** [comment]
Inadvertently fixed it
