### ISSUE TITLE
Not performing complete set of searches

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#35]
Using commit 12aec7b

Script starts and determines that 20 mobile searches left:
```
accountremoved@domainremoved: using saved cookies
accountremoved@domainremoved: current points: 13456
accountremoved@domainremoved: desktop left: 30
accountremoved@domainremoved: mobile left: 20
accountremoved@domainremoved: next search in: 148 seconds
accountremoved@domainremoved: 1/20: mobile search: santa catarina pinula
accountremoved@domainremoved: next search in: 112 seconds

```
..script executes fine..
```
accountremoved@domainremoved: 13/20: mobile search: ford
accountremoved@domainremoved: next search in: 24 seconds
accountremoved@domainremoved: 14/20: mobile search: popular now
accountremoved@domainremoved: searches done
accountremoved@domainremoved: points earned: 111
accountremoved@domainremoved: total points: 13567
```
but then stopped at 14 of 20 searches?
Shouldn't it have continued all the way to 20 mobile searches? Or is there randomization also applied to how many searches are done +/- the total possible to make it look less precise?
All 30 desktop searches were completed.

**Comment by zengfu94** [comment]
Okay so the searching algorithm adds query_salt, desktop_left and mobile_left together so its possible for it to not do all searches for both. The algorithm doesn't do them randomly and tries very hard to complete all for both and look humanlike doing so but there's some anomalies.

**Comment by AnthonyBe** [comment]
Got it.

I figured there was a salt being added to make the humanization but just wanted to check it was all working correctly.

**Comment by Brenex** [comment]
It might be worth showing in the script when it has chosen not to perform a complete search so people don't keep asking about it?

**Comment by zengfu94** [comment]
Just got back from trip, latest commit should let ya know now @Brenex
