### ISSUE TITLE
common settings overwritten

### ISSUE THREAD

**Issue by adambird79** [zengfu94/MicrosoftRewards#36]
Hi, 

I have made some changes to the common.py but every time I launch the script these are overwritten with the default settings.

The only way I have found to stop this is to rename the git.exe in bing.py file. 

Thanks

**Comment by zengfu94** [comment]
I'll look into this, does it say its performing an update each time?

**Comment by adambird79** [comment]
Yes every time I run it updates, to keep the settings I find the line which points to the git.exe and change the name to stop the update.

Thanks

**Comment by zengfu94** [comment]
Have you committed things offline? It compares repo commit hash with git rev-parse output and if different performs an update

**Comment by adambird79** [comment]
I just editied the common.py locally. Do I need to do additional steps ?

thanks

**Comment by zengfu94** [comment]
Alright so I've figured it out, I used sed to do the editting and sed is not installed by defualt on all Windows machines. I'll switch to something more widely available or include sed in the package.

**Comment by zengfu94** [comment]
This is fixed.
