### ISSUE TITLE
SyntaxError bing.py, line 239 "if hpm = True:"

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#4]
C:\Users\Anthony>"D:\Python27\python.exe" C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 239
    if hpm = True:
                ^
SyntaxError: invalid syntax

Removing colon at end of the line had no effect (but thought I'd mention in case that is also an issue)

**Comment by zengfu94** [comment]
oh derp by me lmao

**Comment by AnthonyBe** [comment]
That's why we have testers to support the coders :)

**Comment by zengfu94** [comment]
git pull

**Comment by AnthonyBe** [comment]
resolved
