### ISSUE TITLE
getting error when running

### ISSUE THREAD

**Issue by kkasberg** [zengfu94/MicrosoftRewards#44]
I am getting the following error when trying to run bing.py

I did a git pull to ensure that everything is up to date.

```
Traceback (most recent call last):
  File "bing.py", line 22, in <module>
    import googleTrends as gt
  File "/home/kevin/MicrosoftRewards/googleTrends.py", line 3, in <module>
    import common
  File "/home/kevin/MicrosoftRewards/common.py", line 11
    selectedLocale = United States
```

**Comment by zengfu94** [comment]
do you mind running git reset --hard then git pull and reruning. It looks like some things in common.py got written wrong, I'll look at it later today.

**Comment by kkasberg** [comment]
that did it.   Many thanks!

**Comment by zengfu94** [comment]
Run a git pull I just pushed a fix for that. The daily reward had weird characters.
