### ISSUE TITLE
when logging output to a file it gets stuck at "Checking for updates..."

### ISSUE THREAD

**Issue by kkasberg** [zengfu94/MicrosoftRewards#45]
I would like to output the script details to a log file, but when I run 

`
python bing.py 2>&1 bing.log 

`
All I get is
"Checking for updates..."

**Comment by zengfu94** [comment]
I'll add this in, I don't know why that wouldn't work but thanks for suggestions.

**Comment by kkasberg** [comment]
While offering suggestions, it would be really cool to get an e-mail at the end of the run which would show a breakdown by account of how many points were earned, how many points the accounts had etc.   It would be a lot easier than checking each day that it was running correctly.

**Comment by zengfu94** [comment]
Have you heard of Pushbullet? Sending an email would require less secure apps on and alot more dependencies.

**Comment by kkasberg** [comment]
How would one use pushbullet to get the summery file?   I may be missing something.

**Comment by zengfu94** [comment]
Pushbullet can send files or plain text

**Comment by zengfu94** [comment]
So basically with pushbullet, (its by google) so you download the app on your phone/pc and the bot can use your api key to send you results

**Comment by zengfu94** [comment]
how does this look: https://imgur.com/WZZGDw4
Notification with link to download report.

**Comment by kkasberg** [comment]
it looks good, thanks!

**Comment by zengfu94** [comment]
Notifications on completion, error and total points earned are available in commit: https://github.com/zengfu94/MicrosoftRewards/commit/885d16a9cb4cda36ae94a89353744eec38af8d0c
Also, bot.log is outputted by default with complete log of what went on in the cmd window.
