### ISSUE TITLE
PIP install doesn't actually run

### ISSUE THREAD

**Issue by Brenex** [zengfu94/MicrosoftRewards#49]
Here you can see the command is echoed but doesn't actually run. The next line is me actually typing it in myself: 

![capture](https://user-images.githubusercontent.com/3178983/32136760-9d4aec4a-bbe1-11e7-8a7f-e9acdad1bf5d.JPG)

also, if you are going to run commands automatically to install, why not also include "requests setuptools pip"? Thanks for your work on this project!

**Comment by zengfu94** [comment]
Oh wow. Thanks for heads-up

**Comment by zengfu94** [comment]
Python doesn't like automated pip installs so I changed the "Installing" to "Run the following command" requests is only included in the command if it is not installed, same with bs4.
