### ISSUE TITLE
accounts.txt not found!

### ISSUE THREAD

**Issue by AnthonyBe** [zengfu94/MicrosoftRewards#5]
Current git pull:

C:\Users\Anthony>"D:\Python27\python.exe" C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py
Did you remember to rename accounts.txt.dist to accounts.txt?
accounts.txt not found!

Accounts.txt exists and contains:

myaccountname@realdomain.com>myrealpassword>Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0>Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0

**Comment by zengfu94** [comment]
make sure its accounts.txt and not accounts.txt.txt

**Comment by AnthonyBe** [comment]
Confirmed all lower case and no hidden/double file extension.

It had been working fine until this last git pull

**Comment by zengfu94** [comment]
if theres another window with the script open/error'd it will block python from opening accounts.txt

**Comment by AnthonyBe** [comment]
Double-checked. Close all other windows. Re-opened fresh CMD prompt window and re-ran.

Same error.

**Comment by zengfu94** [comment]
the latest commit will give a more descriptive error, give it a try please

**Comment by AnthonyBe** [comment]
Grabbed current commit. New, more descriptive, error:

C:\Users\Anthony>"D:\Python27\python.exe" C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py
Did you remember to rename accounts.txt.dist to accounts.txt?
Could not find accounts.txt
Traceback (most recent call last):
  File "C:\Temp\MicrosoftRewards\MicrosoftRewards-master\bing.py", line 266, in <module>
    for line in input_file:
NameError: name 'input_file' is not defined

**Comment by AnthonyBe** [comment]
.. and in case it is pertinent, I'm running this on Windows 10 x64 with Python 2.7.13

**Comment by zengfu94** [comment]
Please check out this screenshot: https://imgur.com/a/p8jH3 right now you can't run it if you're not in the same directory as accounts.txt/bing.py

**Comment by AnthonyBe** [comment]
Got it. Yep, I can run if I do as you did and run from the actual directory containing accounts.txt and bing.py

**Comment by zengfu94** [comment]
Sorry bout confusion, I'll see if I can make it run from any directory.
