### ISSUE TITLE
Searches not earning Points

### ISSUE THREAD

**Issue by MonkeyDoo** [zengfu94/MicrosoftRewards#50]
Anyone else having trouble with bot not earning points for searches? I will watch the bot perform the searches but if I log into my account the searches are not registering and the account is not earning. If I check the activity of the account though it shows that it logged in. So something is messed up with the bot searching because if I search manual in browser they earn. This account last earned on 10/21 but has been logging in on the bot everyday. I did delete the cookies before searching on 10/26 to see if that was the issue.

![screenshot_4](https://user-images.githubusercontent.com/33231855/32186539-b6b049d0-bd78-11e7-9a81-232edc4e6094.png)

![screenshot_3](https://user-images.githubusercontent.com/33231855/32186491-94170832-bd78-11e7-99e1-ffe8e4b0514d.png)

**Comment by cynthiamurphy12** [comment]
Sorry for time of leave, next commit will fix this.
