### ISSUE TITLE
requests.exceptions.ProxyError:

### ISSUE THREAD

**Issue by rrosajp** [zengfu94/MicrosoftRewards#9]
it gives 
requests.exceptions.ProxyError: None: Max retries exceeded with url: / (Caused by None)
when no proxy in account.txt
can u help to resolve
thanks
here is the error msg
Found accounts.txt
sleeping for 124 seconds
Traceback (most recent call last):
  File "D:\GitHub\z_xbmc\zipsss\MicrosoftRewards-master\bing.py", line 270, in <module>
    pool.map(search_account, accounts)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
requests.exceptions.ProxyError: None: Max retries exceeded with url: / (Caused by None)

**Comment by zengfu94** [comment]
please make sure to remove the >proxy(optional) portion. if no proxy is being used a line in accounts should look like email>password>desktop_ua>mobile_ua

**Comment by rrosajp** [comment]
btw its great concept incorporated once again thanks for quick response

**Comment by zengfu94** [comment]
@rrosajp issue fixed or still facing it?
